//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingoTeamCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BingoTeamCard()
        {
            this.BingoTeamCardSlots = new HashSet<BingoTeamCardSlot>();
        }
    
        public int Id { get; set; }
        public int BingoTeamId { get; set; }
        public int BingoCardId { get; set; }
    
        public virtual BingoCard BingoCard { get; set; }
        public virtual BingoTeam BingoTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BingoTeamCardSlot> BingoTeamCardSlots { get; set; }
    }
}
