//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingoEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BingoEvent()
        {
            this.BingoCards = new HashSet<BingoCard>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WomId { get; set; }
        public Nullable<long> SourceChannelId { get; set; }
        public Nullable<long> TargetChannelId { get; set; }
        public Nullable<long> EmojiYesId { get; set; }
        public string EmojiNoId { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BingoCard> BingoCards { get; set; }
    }
}
