//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingoTeamCardSlot
    {
        public int Id { get; set; }
        public int BingoTeamCardId { get; set; }
        public int BingoCardSlotId { get; set; }
        public string DateApproved { get; set; }
        public string DateDenied { get; set; }
    
        public virtual BingoCardSlot BingoCardSlot { get; set; }
        public virtual BingoTeamCard BingoTeamCard { get; set; }
    }
}
