//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorruptModel : DbContext
    {
        public CorruptModel()
            : base("name=CorruptModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Boss> Bosses { get; set; }
        public virtual DbSet<BotConfiguration> BotConfigurations { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<ChatLog> ChatLogs { get; set; }
        public virtual DbSet<DiscordUser> DiscordUsers { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<hunt_bossdrops> hunt_bossdrops { get; set; }
        public virtual DbSet<hunt_bosses> hunt_bosses { get; set; }
        public virtual DbSet<hunt_team_drops> hunt_team_drops { get; set; }
        public virtual DbSet<hunt_team_members> hunt_team_members { get; set; }
        public virtual DbSet<hunt_teams> hunt_teams { get; set; }
        public virtual DbSet<PlayerPet> PlayerPets { get; set; }
        public virtual DbSet<PointMutation> PointMutations { get; set; }
        public virtual DbSet<PointStore> PointStores { get; set; }
        public virtual DbSet<RunescapeAccount> RunescapeAccounts { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Toggle> Toggles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
