//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscordUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscordUser()
        {
            this.RunescapeAccounts = new HashSet<RunescapeAccount>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<long> DiscordId { get; set; }
        public Nullable<System.DateTime> OriginallyJoinedAt { get; set; }
        public bool BlacklistedForPromotion { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public int Points { get; set; }
        public int RankId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunescapeAccount> RunescapeAccounts { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
