//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerPet
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DropDate { get; set; }
        public Nullable<int> BossId { get; set; }
        public Nullable<int> RunescapeAccountId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> LevelOrKcGotten { get; set; }
    
        public virtual Boss Boss { get; set; }
        public virtual RunescapeAccount RunescapeAccount { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
