//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunescapeAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RunescapeAccount()
        {
            this.PlayerPets = new HashSet<PlayerPet>();
        }
    
        public int Id { get; set; }
        public string rsn { get; set; }
        public Nullable<int> wom_id { get; set; }
        public Nullable<int> DiscordUserId { get; set; }
        public string account_type { get; set; }
    
        public virtual DiscordUser DiscordUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerPet> PlayerPets { get; set; }
    }
}
