//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.TheHunt.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class corruptosEntities : DbContext
    {
        public corruptosEntities()
            : base("name=corruptosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiscordUser> DiscordUsers { get; set; }
        public virtual DbSet<hunt_bossdrops> hunt_bossdrops { get; set; }
        public virtual DbSet<hunt_bosses> hunt_bosses { get; set; }
        public virtual DbSet<hunt_team_drops> hunt_team_drops { get; set; }
        public virtual DbSet<hunt_team_members> hunt_team_members { get; set; }
        public virtual DbSet<hunt_teams> hunt_teams { get; set; }
    }
}
