//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorruptOSBot.CorruptPoints
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PointStore()
        {
            this.PointMutations = new HashSet<PointMutation>();
        }
    
        public int Id { get; set; }
        public string StoreItemName { get; set; }
        public int StoreItemValue { get; set; }
        public string StoreItemDescription { get; set; }
        public string StoreItemImage { get; set; }
        public string StoreItemCommand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointMutation> PointMutations { get; set; }
    }
}
